routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::get('administracion', function () {
    return view('administrador.masterpage');
});

Route::get('catalogo', function () {
    return view('administrador.catalogos');
});



//SERVICIOS
Route::resource('servicio', 'ServicioController');

//PRODUCTOS
Route::resource('producto', 'ProductoController');

//TIPO
Route::resource('tipo', 'TipoController');

//MARCA
Route::resource('marca', 'MarcaController');

//USUARIO
Route::resource('usuario', 'UsuarioController');

//BARBERIA
Route::resource('barberias', 'BarberiaController');


Route::resource('comentarios', 'ComentarioController');

app/Barberia.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Barberia extends Model
{
    protected $table = "barberia";
    protected $primaryKey = "idB";
    public $timestamps = false;

    protected $fillable = [
        
        'nombreB',
        'latitud',
        'longitud',
        'direccion',
        'propietario',
        'telefono',
        'horario',
    ];
}

app/Http/Controllers/BarberiaController.php
<?php

namespace App\Http\Controllers;
use Yajra\Datatables\Datatables;

use App\Barberia;

use Illuminate\Http\Request;

class BarberiaController extends Controller
{

     public function index(Request $request)
    {
        if ($request->ajax()) {
            $data = Barberia::all();
            return Datatables::of($data)
                    ->addIndexColumn()
                    ->addColumn('action', function($row){
                           $btn = '<a href="javascript:void(0)" data-toggle="tooltip" 
                                    data-id="'.$row->idB.'" data-original-title="Edit" class="edit btn btn-primary btn-sm editItem"><img src="https://img.icons8.com/ios/24/000000/edit.png"/></a>';
   
                           $btn = $btn.' <a href="javascript:void(0)" data-toggle="tooltip"  data-id="'.$row->idB.'" data-original-title="Delete" class="btn btn-danger btn-sm deleteItem"><img src="https://img.icons8.com/ios/24/000000/trash.png"/></a><input type="hidden" class="form-control" id="editBtn"  value="'.$row->idM.'">';
                       
                            return $btn;
                    })
                    ->rawColumns(['action'])
                    ->make(true);
        }
      
        return view('barberias.index');
    }

   
    public function store(Request $request)
    {                                    
                               

        $barberia = Barberia::updateOrCreate(['idB' => $request->barberia_id]);
        $barberia->nombreB = $request->input("nombreB");
        $barberia->latitud = $request->input("latitud");
        $barberia->longitud = $request->input("longitud");
        $barberia->direccion = $request->input("direccion");
        $barberia->propietario = $request->input("propietario");
        $barberia->telefono = $request->input("telefono");
        $barberia->horario = $request->input("horario");
        $barberia->save();

        return response()->json(['success'=>'Item saved successfully.']);


         /* Barberia::updateOrCreate(['idB' => $request->barberia_id],
                ['nombreB' => $request->nombreB],
                ['latitud' => $request->latitud],
                ['longitud' => $request->longitud],
                ['direccion' => $request->direccion],
                ['propietario' => $request->propietario],
                ['telefono' => $request->telefono],
                ['horario' => $request->horario],
            );       
   
        return response()->json(['success'=>'Item saved successfully.']);*/
        
    }
    /*
    public function store(Request $request)
    {
        $marca = new Marca();
        $marca->nombreM = $request->input("nombreM");
        $marca->save();

        return redirect()->route('marca.index')
        ->with("exito" , "La marca fue registrada correctamente")
        ->with("Nombre marca" , $marca->nombreM);
    }*/

    /**
     * Display the specified resource.
     *
     * @param  \App\cr  $cr
     * @return \Illuminate\Http\Response
     */
  /*  public function show(Marca $marca)
    {
        return view('marcas.show',compact('marca'));
    }*/

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\cr  $cr
     * @return \Illuminate\Http\Response
     */
   
    public function edit($id)
    {
        $barberia = Barberia::find($id);
        return response()->json($barberia);
    }


    public function destroy($id)
    {
       Barberia::find($id)->delete();
     
       return response()->json(['success'=>'barberia deleted successfully.']);
    }
}

resources/views/barberia/edit.blade.php
@extends('layout')
  
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Editar barberia </h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('barberias.index') }}"> volver</a>
        </div>
    </div>
</div>
   


<form action="{{ route('barberias.update', $barberia->idB) }}" method="POST">
    @csrf
    @method('PUT')
  
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
          
            <div class="form-group">
                <strong>Nombre </strong>   
                <input type="text" name="nombreB" class="form-control" value="{{ $barberia->nombreB }} ">
            </div>
            <div class="form-group">
                <strong>latitud</strong>   
                <input type="text" name="latitud" class="form-control"  value="{{ $barberia->latitud }} ">
            </div>
            <div class="form-group">
                <strong>longitud</strong>   
                <input type="text" name="longitud" class="form-control" value="{{ $barberia->longitud }} " >
            </div>
            <div class="form-group">
                <strong>direccion</strong>   
                <input type="text" name="direccion" class="form-control" value="{{ $barberia->direccion }} " >
            </div>
            <div class="form-group">
                <strong>propietario</strong>   
                <input type="text" name="propietario" class="form-control" value="{{ $barberia->propietario }} " >
            </div>
            <div class="form-group">
                <strong>telefono</strong>   
                <input type="text" name="telefono" class="form-control"  value="{{ $barberia->telefono }} " >
            </div>
            <div class="form-group">
                <strong>horario</strong>   
                <input type="text" name="horario" class="form-control" value="{{ $barberia->horario }} " >
            </div>

        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Editar</button>
        </div>
    </div>
   
</form>
@endsection

resources/views/barberia/editar.blade.php
@extends('layout')
  
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Editar marca </h2>
        </div>
       
    </div>
</div>
   


<form action="{{ route('barberias.update', $barberia->idB) }}" method="POST">
    @csrf
    @method('PUT')
  
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nombre :</strong>   
                <input type="text" name="nombreM" class="form-control" value="{{ $marca->nombreM }}">
            </div>
            <div class="form-group">
                <strong>latitud</strong>   
                <input type="text" name="latitud" class="form-control" value="{{ $marca->latitud }}">
            </div>
            <div class="form-group">
                <strong>longitud:</strong>   
                <input type="text" name="longitud" class="form-control" value="{{ $marca->longitud }}">
            </div>
            <div class="form-group">
                <strong>direccion:</strong>   
                <input type="text" name="direccion" class="form-control" value="{{ $marca->direccion }}">
            </div>
            <div class="form-group">
                <strong>propietario:</strong>   
                <input type="text" name="propietario" class="form-control" value="{{ $marca->propietario }}">
            </div>
            <div class="form-group">
                <strong>telefono:</strong>   
                <input type="text" name="telefono" class="form-control" value="{{ $marca->telefono }}">
            </div>
          
            <div class="form-group">
                <strong>horario:</strong>   
                <input type="text" name="horario" class="form-control" value="{{ $marca->horario }}">
            </div>

        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Editar</button>
        </div>
    </div>
   
</form>
@endsection

resources/views/barberia/index.blade.php
@extends('administrador.masterpage')


@section('contenido')

@extends('layout')
<!--Se llama al layout-->

@section('content')
<div class="container">
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Lista de barberias</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-success" href="{{ route('barberias.create') }}"><img src="https://img.icons8.com/ios/24/000000/plus.png" /></a>
        </div>
    </div>
</div>

@if ($message = Session::get('exito'))
<div class="alert alert-success">
    <p>{{ $message }}</p>
</div>
@endif

<table class="table table-bordered ">
    <tr>
        <th>ID</th>
        <th>nombre</th>
        <th>latitud</th>
        <th>longitud</th>
        <th>direccion</th>
        <th>propietario</th>
        <th>telefono</th>
        <th>horario</th>
        <th>Acciones</th>
    </tr>
    @foreach ($barberias as $barberia)
        <tr>
            <td>{{ $barberia->idB }}</td>
            <td>{{ $barberia->nombreB }}</td>
            <td>{{ $barberia->latitud }}</td>
            <td>{{ $barberia->longitud }}</td>
            <td>{{ $barberia->direccion }}</td>
            <td>{{ $barberia->propietario }}</td>
            <td>{{ $barberia->telefono }}</td>
            <td>{{ $barberia->horario }}</td>

        <td>
           <!--<form action="{{ route('barberias.destroy', $barberia->idB) }}" method="POST">


                <a class="btn btn-primary" href="{{ route('barberias.edit',$barberia->idB) }}"><img src="https://img.icons8.com/ios/24/000000/edit.png" /></a>

                @csrf
                @method('DELETE')

                <button type="submit" class="btn btn-danger"><img src="https://img.icons8.com/ios/24/000000/trash.png" /></button>
            </form> -->
        </td>
    </tr>
    @endforeach
</table>
<div class="links"> {{ $barberias->links() }} </div>
</div>
@endsection
@endsection

resources/views/barberia/new.blade.php
@extends('layout')
  
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Agregar barberia</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('barberias.index') }}"> volver</a>
        </div>
    </div>
</div>
   
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> Error durante el procedimiento.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
<div id="map"></div>

    <input type="text" id="coords" />
<form action="{{ route('barberias.store') }}" method="POST">
    @csrf
  
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nombre </strong>   
                <input type="text" name="nombreB" class="form-control" >
            </div>
            <div class="form-group">
                <strong>latitud</strong>   
                <input type="text" name="latitud" class="form-control" >
            </div>
            <div class="form-group">
                <strong>longitud</strong>   
                <input type="text" name="longitud" class="form-control" >
            </div>
            <div class="form-group">
                <strong>direccion</strong>   
                <input type="text" name="direccion" class="form-control" >
            </div>
            <div class="form-group">
                <strong>propietario</strong>   
                <input type="text" name="propietario" class="form-control" >
            </div>
            <div class="form-group">
                <strong>telefono</strong>   
                <input type="text" name="telefono" class="form-control" >
            </div>
            <div class="form-group">
                <strong>horario</strong>   
                <input type="text" name="horario" class="form-control" >
            </div>

        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Crear</button>
        </div>
    </div>
   
</form>
@endsection

resources/views/barberia/nuevo.blade.php
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <title> </title>
    <style>
        html,
        body {
            height: 100%;
            margin: 0;
            padding: 0;
        }

        #map {
            width: 20%;
            height: 20%;
            left:60%;
            top:-50%;
        }

    </style>
</head>

<body>

    <div class="container">
        <div class="col-12">
            <div class="col-6">

                <form action="{{ route('barberias.store') }}" method="POST">
                    @csrf

                    <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <strong>Nombre </strong>
                                <input type="text" name="nombreB" class="form-control">
                            </div>
                            <div class="form-group">
                                <strong>latitud</strong>
                                <input type="text" name="latitud" class="form-control" id="latitud">
                            </div>
                            <div class="form-group">
                                <strong>longitud</strong>
                                <input type="text" name="longitud" class="form-control" id="longitud">
                            </div>
                            <div class="form-group">
                                <strong>direccion</strong>
                                <input type="text" name="direccion" class="form-control">
                            </div>
                            <div class="form-group">
                                <strong>propietario</strong>
                                <input type="text" name="propietario" class="form-control">
                            </div>
                            <div class="form-group">
                                <strong>telefono</strong>
                                <input type="text" name="telefono" class="form-control">
                            </div>
                            <div class="form-group">
                                <strong>horario</strong>
                                <input type="text" name="horario" class="form-control">
                            </div>

                            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                                <button type="submit" class="btn btn-primary">Crear</button>
                            </div>
                        </div>

                </form>

            </div>


            </div>
        </div>

    </div>
    <div class="col-6" id="map"></div>

    <script>
        var marker; //variable del marcador
        var coords = {}; //coordenadas obtenidas con la geolocalización

        //Funcion principal
        initMap = function() {

            //usamos la API para geolocalizar el usuario
            navigator.geolocation.getCurrentPosition(
                function(position) {
                    coords = {
                        lng: position.coords.longitude,
                        lat: position.coords.latitude
                    };
                    setMapa(coords); //pasamos las coordenadas al metodo para crear el mapa


                },
                function(error) {
                    console.log(error);
                });

        }



        function setMapa(coords) {
            //Se crea una nueva instancia del objeto mapa
            var map = new google.maps.Map(document.getElementById('map'), {
                zoom: 16,
                center: new google.maps.LatLng(coords.lat, coords.lng),

            });

            //Creamos el marcador en el mapa con sus propiedades
            //para nuestro obetivo tenemos que poner el atributo draggable en true
            //position pondremos las mismas coordenas que obtuvimos en la geolocalización
            marker = new google.maps.Marker({
                map: map,
                draggable: true,
                animation: google.maps.Animation.DROP,
                position: new google.maps.LatLng(coords.lat, coords.lng),

            });
            //agregamos un evento al marcador junto con la funcion callback al igual que el evento dragend que indica 
            //cuando el usuario a soltado el marcador
            marker.addListener('click', toggleBounce);

            marker.addListener('dragend', function(event) {
                //escribimos las coordenadas de la posicion actual del marcador dentro del input #coords
                document.getElementById("latitud").value = this.getPosition().lat();
                document.getElementById("longitud").value = this.getPosition().lng();

            });
        }

        //callback al hacer clic en el marcador lo que hace es quitar y poner la animacion BOUNCE
        function toggleBounce() {
            if (marker.getAnimation() !== null) {
                marker.setAnimation(null);
            } else {
                marker.setAnimation(google.maps.Animation.BOUNCE);
            }
        }
    </script>
    <script async defer src="https://maps.googleapis.com/maps/api/js?callback=initMap"></script>
</body>

</html>