routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::get('administracion', function () {
    return view('administrador.masterpage');
});

Route::get('catalogo', function () {
    return view('administrador.catalogos');
});



//SERVICIOS
Route::resource('servicio', 'ServicioController');

//PRODUCTOS
Route::resource('producto', 'ProductoController');

//TIPO
Route::resource('tipo', 'TipoController');

//MARCA
Route::resource('marca', 'MarcaController');

//USUARIO
Route::resource('usuario', 'UsuarioController');

//BARBERIA
Route::resource('barberias', 'BarberiaController');


Route::resource('comentarios', 'ComentarioController');

app/Producto.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Producto extends Model
{
    protected $table = "producto";
    protected $primaryKey = "idP";
    public $timestamps = false;

    protected $fillable = ['nombreP','precioP'];
}

app/Http/Controllers/ProductoController.php
<?php

namespace App\Http\Controllers;
use Yajra\Datatables\Datatables;

use App\Producto;

use Illuminate\Http\Request;

class ProductoController extends Controller
{

     public function index(Request $request)
    {
        if ($request->ajax()) {
            $data = Producto::all();
            return Datatables::of($data)
                    ->addIndexColumn()
                    ->addColumn('action', function($row){
                           $btn = '<a href="javascript:void(0)" data-toggle="tooltip" 
                                    data-id="'.$row->idP.'" data-original-title="Edit" class="edit btn btn-primary btn-sm editItem"><img src="https://img.icons8.com/ios/24/000000/edit.png"/></a>';
   
                           $btn = $btn.' <a href="javascript:void(0)" data-toggle="tooltip"  data-id="'.$row->idP.'" data-original-title="Delete" class="btn btn-danger btn-sm deleteItem"><img src="https://img.icons8.com/ios/24/000000/trash.png"/></a><input type="hidden" class="form-control" id="editBtn"  value="'.$row->idP.'">';
                       
                            return $btn;
                    })
                    ->rawColumns(['action'])
                    ->make(true);
        }
      
        return view('productos.index');
    }

   
    public function store(Request $request)
    {                                    
                               

        $producto = Producto::updateOrCreate(['idP' => $request->producto_id]);
        $producto->nombreP = $request->input("nombreP");
        $producto->precioP = $request->input("precioP");
        $producto->save();

        return response()->json(['success'=>'Item saved successfully.']);


         /* Barberia::updateOrCreate(['idB' => $request->barberia_id],
                ['nombreB' => $request->nombreB],
                ['latitud' => $request->latitud],
                ['longitud' => $request->longitud],
                ['direccion' => $request->direccion],
                ['propietario' => $request->propietario],
                ['telefono' => $request->telefono],
                ['horario' => $request->horario],
            );       
   
        return response()->json(['success'=>'Item saved successfully.']);*/
        
    }
    /*
    public function store(Request $request)
    {
        $marca = new Marca();
        $marca->nombreM = $request->input("nombreM");
        $marca->save();

        return redirect()->route('marca.index')
        ->with("exito" , "La marca fue registrada correctamente")
        ->with("Nombre marca" , $marca->nombreM);
    }*/

    /**
     * Display the specified resource.
     *
     * @param  \App\cr  $cr
     * @return \Illuminate\Http\Response
     */
  /*  public function show(Marca $marca)
    {
        return view('marcas.show',compact('marca'));
    }*/

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\cr  $cr
     * @return \Illuminate\Http\Response
     */
   
    public function edit($id)
    {
        $producto = Producto::find($id);
        return response()->json($producto);
    }


    public function destroy($id)
    {
       Producto::find($id)->delete();
     
       return response()->json(['success'=>'Producto deleted successfully.']);
    }
}

resources/views/productos/edit.blade.php
@extends('layout')
  
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Editar producto</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('producto.index') }}"> volver</a>
        </div>
    </div>
</div>
   


<form action="{{ route('producto.update', $producto->idP) }}" method="POST">
    @csrf
    @method('PUT')
  
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nombre producto:</strong>   
                <input type="text" name="nombreP" class="form-control" value="{{ $producto->nombreP }}">
            </div>
            <div class="form-group">
                <strong>Precio:</strong>
                <input type="text" name="precioP" class="form-control" value="{{ $producto->precioP}}">
            </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Editar</button>
        </div>
    </div>
   
</form>
@endsection

resources/views/productos/index.blade.php
@extends('administrador.masterpage')


@section('contenido')

    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css" />
    <link href="https://cdn.datatables.net/1.10.17/css/jquery.dataTables.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.js"></script>
    <script src="https://cdn.datatables.net/1.10.17/js/jquery.dataTables.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>

    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
</head>
<body class="bg-dark">
 <div class="container">
   <div class="row">
     <div class="col-md-12">
       <div class="card mt-5">
         <div class="card-header">
            <div class="col-md-12">
                <h4 class="card-title">
                  <a class="btn btn-success ml-5" href="javascript:void(0)" id="createNewItem"><img src="https://img.icons8.com/ios/24/000000/plus.png"/></a>
                </h4>
            </div>
         </div>
         <div class="card-body">
           <table class="table table-bordered data-table">
                <thead>
                    <tr>
                    <th>Código</th>
                    <th>Nombre</th>
                    <th>Precio</th>

                    <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
        <div class="modal fade" id="ajaxModel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title" id="modelHeading"></h4>
                    </div>
                    <div class="modal-body">
                        <form id="ItemForm" name="ItemForm" class="form-horizontal">
                           <input type="hidden" name="producto_id" id="producto_id">
                                <div class="form-group">
                                <label>Nombre producto</label>
                                <div class="col-md-12">
                                <input id="nombreP" name="nombreP" type="text" placeholder="Ingrese el nombre del producto" class="form-control input-md">
                                    </div>

                            <div class="form-group">
                              <label>Precio</label>
                                <div class="col-sm-12">
                                    <input type="text" class="form-control" id="precioP" name="precioP" placeholder="Ingresar precio producto" value="" maxlength="50" required="">
                                </div>
                            </div>



                            <div class="col-sm-offset-2 col-sm-10">
                             <button type="submit" class="btn btn-primary" id="saveBtn" value="create">Guardar
                             </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
         </div>
       </div>
     </div>
   </div>
 </div>
</body>

<script type="text/javascript">


  $(function () {

    $.ajaxSetup({
          headers: {
              'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
          }
    });

    var table = $('.data-table').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{{ route('producto.index') }}",
        columns: [
            {data: 'DT_RowIndex', name: 'DT_RowIndex'},
            {data: 'nombreP', name: 'nombreP'},
            {data: 'precioP', name: 'precioP'},
            {data: 'action', name: 'action', orderable: false, searchable: false},
        ],

        language: {
          sProcessing: "Procesando...",
          sLengthMenu: "Mostrar _MENU_ objetos",
          sZeroRecords: "No se encontraron objetos similares",
          sEmptyTable: "No se encontraron objetos similares",
          sInfo: "Mostrando objetos del _START_ al _END_ de un total de _TOTAL_ objetos",
          sInfoEmpty: "Mostrando objetos del 0 al 0 de un total de 0 objetos",
          sInfoFiltered: "(filtrado de un total de _MAX_ objetos)",
          sInfoPostFix: "",
          sSearch: "Buscar:",
          sUrl: "",
          sInfoThousands: ",",
          sLoadingRecords: "Cargando...",
          oPaginate: {
            sFirst: "Primero",
            sLast: "Último",
            sNext: "Siguiente",
            sPrevious: "Anterior"
          },
          oAria: {
            sSortAscending: ": Activar para ordenar la columna de manera ascendente",
            sSortDescending: ": Activar para ordenar la columna de manera descendente"
          }
            }
    });

    $('#createNewItem').click(function () {
        $('#saveBtn').val("Agregar producto");
        $('#producto_id').val('');
        $('#ItemForm').trigger("reset");
        $('#modelHeading').html("Agregar producto");
        $('#ajaxModel').modal('show');
    });



    $('body').on('click', '.editItem', function () {

    $.ajaxSetup({
          headers: {
              'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
          }
    });
      var producto_id = $(this).data("id");
      $.get("{{ route('producto.index') }}" +'/' + producto_id +'/edit', function (data) {
          $('#modelHeading').html("Editar producto");
          $('#saveBtn').val("edit-user");
          $('#ajaxModel').modal('show');
          $('#producto_id').val(data.idP);
          $('#nombreP').val(data.nombreP);
          $('#precioP').val(data.precioP);
      })



   });

    $('#saveBtn').click(function (e) {
        e.preventDefault();
        $(this).html('Guardando...');

        $.ajax({
          data: $('#ItemForm').serialize(),
          url: "{{ route('producto.store') }}",
          type: "POST",
          dataType: 'json',
          success: function (data) {

              $('#ItemForm').trigger("reset");
              $('#ajaxModel').modal('hide');
              table.draw();

          },
          error: function (data) {
              console.log('Error:', data);
              $('#saveBtn').html('Guardando');
          }
      });
    });



    $('body').on('click', '.deleteItem', function () {

        var producto_id = $(this).data("id");
        confirm("¿Esta seguro de eliminar el producto? ");

        $.ajax({
            type: "DELETE",
            url: "{{ route('producto.store') }}"+'/'+producto_id,
            success: function (data) {
                table.draw();
            },
            error: function (data) {
                console.log('Error:', data);
            }
        });
    });

  });
</script>
@endsection

resources/views/productos/new.blade.php
@extends('layout')
  
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Agregar producto</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('producto.index') }}"> volver</a>
        </div>
    </div>
</div>
   
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> Error durante el procedimiento.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
<form action="{{ route('producto.store') }}" method="POST">
    @csrf
  
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nombre producto</strong>   
                <input type="text" name="nombreP" class="form-control" >
            </div>
            <div class="form-group">
                <strong>Precio:</strong>
                <input type="text" name="precioP" class="form-control" >
            </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
        <button type="submit" class="btn btn-primary">Crear</button>
        </div>
    </div>
   
</form>
@endsection

resources/views/productos/show.blade.php
@extends('layout')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Ver Producto</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('producto.index') }}"> Volver</a>
            </div>
        </div>
    </div>
   
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nombre Producto:</strong>
                {{ $producto->nombreP }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Precio:</strong>
                {{ $producto->precioP }}
            </div>
        </div>
    </div>
@endsection